# Gradle ??? ??
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError
org.gradle.java.home=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Android ?? ??
android.useAndroidX=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=true
android.suppressUnsupportedCompileSdk=35
